import type { GatewayPayload } from "@lunibee/types";

/** Gateway operation codes defined by Discord. */
export const GatewayOpcodes = { Dispatch: 0, Heartbeat: 1, Identify: 2, PresenceUpdate: 3, VoiceStateUpdate: 4, Resume: 6, Reconnect: 7, RequestGuildMembers: 8, InvalidSession: 9, Hello: 10, HeartbeatAck: 11 } as const;
/** Gateway lifecycle states. */
export type GatewayState = "disconnected" | "connecting" | "hello" | "identifying" | "resuming" | "ready" | "reconnecting" | "closed";
/** Gateway error with an optional Discord close code. */
export class GatewayError extends Error { /** Discord close code associated with the error. */ public readonly code?: number; /** Creates a Gateway error. @param message Error message. @param code Discord close code. @param options Native error options. */ public constructor(message: string, code?: number, options?: ErrorOptions) { super(message, options); this.name = "GatewayError"; this.code = code; } }
/** Gateway connection options. */
export interface GatewayOptions {
    /** Bot authentication token. */ token: string;
    /** Gateway intent bitfield. */ intents: number;
    /** Zero-based shard identifier. */ shardId?: number;
    /** Total shard count. */ shardCount?: number;
    /** Whether automatic reconnect is enabled. */ reconnect?: boolean;
    /** Maximum reconnect attempts before giving up. */ maxReconnectAttempts?: number;
    /** Base reconnect delay in milliseconds. */ reconnectBaseDelay?: number;
    /** Maximum reconnect delay in milliseconds. */ reconnectMaxDelay?: number;
    /** Heartbeat acknowledgement timeout in milliseconds. */ heartbeatAckTimeout?: number;
    /** Zombie connection timeout in milliseconds. */ zombieTimeout?: number;
}
/** Callback invoked for Gateway events. */
type GatewayListener = (data: unknown) => unknown;

/** A Bun-native Discord Gateway connection with strict lifecycle, heartbeat, resume, reconnect, and zombie detection. */
export class Gateway {
    /** Current Gateway lifecycle state. */ public state: GatewayState = "disconnected";
    #options: Required<GatewayOptions>; #ws?: WebSocket; #sequence: number | null = null; #sessionId?: string; #resumeURL?: string;
    #heartbeatTimer?: ReturnType<typeof setInterval>; #initialHeartbeat?: ReturnType<typeof setTimeout>; #heartbeatAckTimer?: ReturnType<typeof setTimeout>; #heartbeatACK = true; #heartbeatInterval = 0; #heartbeatSentAt = 0;
    #lastMessageAt = 0; #zombieTimer?: ReturnType<typeof setInterval>; #zombieReported = false; #closed = false; #attempt = 0; #reconnectTimer?: ReturnType<typeof setTimeout>;
    #connectPromise?: Promise<void>; #resolveConnect?: () => void; #rejectConnect?: (error: GatewayError) => void;
    readonly #listeners = new Map<string, Set<GatewayListener>>(); readonly #sendTimestamps: number[] = [];

    /** Creates a Gateway connection manager. @param options Gateway configuration. @throws {TypeError} If token or intents are invalid. @throws {RangeError} If shard or timeout configuration is invalid. */
    public constructor(options: GatewayOptions) { if (!options.token?.trim()) throw new TypeError("A Gateway token is required."); if (!Number.isInteger(options.intents) || options.intents < 0) throw new TypeError("Gateway intents must be a non-negative integer."); this.#options = { shardId: 0, shardCount: 1, reconnect: true, maxReconnectAttempts: Infinity, reconnectBaseDelay: 1000, reconnectMaxDelay: 30000, heartbeatAckTimeout: 10000, zombieTimeout: 30000, ...options }; if (this.#options.shardId < 0 || this.#options.shardId >= this.#options.shardCount) throw new RangeError("Gateway shardId must be within the configured shard count."); if (this.#options.zombieTimeout <= this.#options.heartbeatAckTimeout) throw new RangeError("Gateway zombieTimeout must be greater than heartbeatAckTimeout."); }
    /** Opens a Gateway connection and settles when READY is received. @param url Gateway WebSocket URL. @returns A promise fulfilled after the Gateway reaches READY. @throws {GatewayError} If connection establishment permanently fails. */
    public connect(url = "wss://gateway.discord.gg/?v=10&encoding=json"): Promise<void> { if (this.state === "closed") throw new GatewayError("Gateway has been permanently closed."); if (this.#connectPromise) return this.#connectPromise; this.#closed = false; this.#setState("connecting"); this.#connectPromise = new Promise<void>((resolve, reject) => { this.#resolveConnect = resolve; this.#rejectConnect = reject; this.#open(url); }); return this.#connectPromise; }
    /** Permanently closes the connection and clears all timers. @returns Nothing. */
    public close(): void { this.#closed = true; this.#clearTimers(); this.#settleConnect(new GatewayError("Gateway connection closed before READY.")); const ws = this.#ws; this.#ws = undefined; try { ws?.close(1000, "Client closed connection"); } catch (error) { this.#emitError(error); } this.#setState("closed"); }
    /** Registers an event listener. @param event Event name. @param listener Listener callback. @returns This Gateway. @throws {TypeError} If event or listener is invalid. */ public on(event: string, listener: GatewayListener): this { if (!event || typeof listener !== "function") throw new TypeError("Gateway event and listener are required."); let listeners = this.#listeners.get(event); if (!listeners) this.#listeners.set(event, listeners = new Set()); listeners.add(listener); return this; }
    /** Removes an event listener. @param event Event name. @param listener Listener callback. @returns This Gateway. */ public off(event: string, listener: GatewayListener): this { this.#listeners.get(event)?.delete(listener); return this; }
    /** Sends a validated Gateway payload subject to a conservative send budget. @param payload Gateway payload. @returns True when sent successfully. */ public send(payload: GatewayPayload): boolean { if (!payload || !Number.isInteger(payload.op)) throw new TypeError("Gateway payload must contain an integer opcode."); if (this.#ws?.readyState !== WebSocket.OPEN) return false; const now = Date.now(); while (this.#sendTimestamps.length && now - this.#sendTimestamps[0]! >= 60000) this.#sendTimestamps.shift(); if (this.#sendTimestamps.length >= 115) { this.#emitError(new GatewayError("Gateway send rate budget exhausted.")); return false; } try { this.#ws.send(JSON.stringify(payload)); this.#sendTimestamps.push(now); return true; } catch (error) { this.#emitError(error); return false; } }
    /** Sends a presence update through the Gateway. @param data Presence payload. @returns True when sent. */ public setPresence(data: Record<string, unknown>): boolean { return this.send({ op: GatewayOpcodes.PresenceUpdate, d: data, s: null, t: null }); }
    /** Sends a voice-state update through the Gateway. @param data Voice state payload. @returns True when sent. */ public setVoiceState(data: Record<string, unknown>): boolean { return this.send({ op: GatewayOpcodes.VoiceStateUpdate, d: data, s: null, t: null }); }
    /** Requests guild members through the Gateway. @param data Guild member request payload. @returns True when sent. */ public requestGuildMembers(data: Record<string, unknown>): boolean { return this.send({ op: GatewayOpcodes.RequestGuildMembers, d: data, s: null, t: null }); }

    /** Opens a WebSocket and installs Gateway dispatch handlers. @param url Gateway WebSocket URL. @returns Nothing. */
    #open(url: string): void { if (this.#closed) return; let ws: WebSocket; try { ws = new WebSocket(url); } catch (error) { const failure = this.#normalizeError(error); this.#emitError(failure); if (this.#options.reconnect) { this.#setState("reconnecting"); this.#scheduleReconnect(); } else this.#settleConnect(failure); return; } this.#ws = ws; ws.addEventListener("open", () => { this.#lastMessageAt = Date.now(); this.#zombieReported = false; this.#startZombieDetection(); this.#emit("open", undefined); }); ws.addEventListener("message", event => { this.#lastMessageAt = Date.now(); this.#zombieReported = false; this.#message(ws, String(event.data)); }); ws.addEventListener("close", event => this.#close(ws, event.code)); ws.addEventListener("error", () => this.#emitError(new GatewayError("Gateway WebSocket error"))); }
    /** Detects an open socket whose heartbeat and traffic liveness are stale. @returns Nothing. */
    #startZombieDetection(): void { if (this.#zombieTimer) clearInterval(this.#zombieTimer); const interval = Math.max(1, Math.min(250, this.#options.heartbeatAckTimeout, this.#options.zombieTimeout / 2)); this.#zombieTimer = setInterval(() => { if (this.#closed || this.#ws?.readyState !== WebSocket.OPEN || this.#lastMessageAt === 0) return; const silentFor = Date.now() - this.#lastMessageAt; const deadline = Math.max(this.#options.zombieTimeout, this.#heartbeatInterval + this.#options.heartbeatAckTimeout); if (silentFor < deadline || this.#zombieReported) return; this.#zombieReported = true; const error = new GatewayError(`Gateway connection appears stale after ${silentFor}ms without traffic.`); this.#emit("zombie", { silentFor, timeout: deadline }); this.#emitError(error); try { this.#ws.close(1001, "Zombie Gateway connection"); } catch (closeError) { this.#emitError(closeError); } }, interval); }
    /** Parses and routes a Gateway payload. @param ws Socket that received the payload. @param raw Raw payload string. @returns Nothing. */
    #message(ws: WebSocket, raw: string): void { let payload: GatewayPayload; try { payload = JSON.parse(raw) as GatewayPayload; } catch (error) { this.#emitError(new GatewayError("Gateway returned invalid JSON", undefined, { cause: error })); ws.close(1002, "Invalid JSON"); return; } if (!payload || typeof payload.op !== "number") { this.#emitError(new GatewayError("Gateway returned an invalid payload")); ws.close(1002, "Invalid payload"); return; } if (typeof payload.s === "number") this.#sequence = payload.s; switch (payload.op) { case GatewayOpcodes.Dispatch: this.#handleDispatch(payload.t, payload.d); break; case GatewayOpcodes.Hello: this.#handleHello(payload.d); break; case GatewayOpcodes.Heartbeat: this.#sendHeartbeat(); break; case GatewayOpcodes.HeartbeatAck: this.#heartbeatACK = true; this.#clearHeartbeatAckTimer(); this.#emit("heartbeatAck", payload.d); break; case GatewayOpcodes.Reconnect: ws.close(1001, "Server requested reconnect"); break; case GatewayOpcodes.InvalidSession: this.#sessionId = undefined; this.#sequence = null; this.#emit("invalidSession", payload.d); ws.close(1000, "Invalid session"); break; } }
    /** Handles a Gateway dispatch event and captures READY session metadata. @param event Gateway dispatch event name. @param data Dispatch payload. @returns Nothing. */
    #handleDispatch(event: string | null, data: unknown): void { if (event === "READY") { const ready = data as { session_id?: unknown; resume_gateway_url?: unknown }; if (typeof ready?.session_id !== "string" || typeof ready?.resume_gateway_url !== "string") { this.#emitError(new GatewayError("Gateway READY payload is missing session information")); return; } this.#sessionId = ready.session_id; this.#resumeURL = ready.resume_gateway_url; this.#attempt = 0; this.#setState("ready"); this.#settleConnect(); this.#emit("ready", data); } this.#emit(event ?? "dispatch", data); }
    /** Handles HELLO and starts the heartbeat/identify lifecycle. @param data HELLO payload. @returns Nothing. */
    #handleHello(data: unknown): void { const interval = (data as { heartbeat_interval?: unknown })?.heartbeat_interval; if (typeof interval !== "number" || !Number.isFinite(interval) || interval <= 0) { this.#emitError(new GatewayError("Gateway HELLO payload contains an invalid heartbeat interval")); this.#ws?.close(1002, "Invalid heartbeat interval"); return; } this.#heartbeatInterval = interval; this.#setState(this.#sessionId && this.#sequence !== null && this.#resumeURL ? "resuming" : "hello"); this.#startHeartbeat(interval); this.#identifyOrResume(); }
    /** Sends RESUME for a valid session or IDENTIFY for a new session. @returns Nothing. */
    #identifyOrResume(): void { if (this.#sessionId && this.#sequence !== null && this.#resumeURL) { this.#setState("resuming"); this.send({ op: GatewayOpcodes.Resume, d: { token: this.#options.token, session_id: this.#sessionId, seq: this.#sequence }, s: null, t: null }); return; } this.#setState("identifying"); this.send({ op: GatewayOpcodes.Identify, d: { token: this.#options.token, intents: this.#options.intents, properties: { os: "linux", browser: "lunibee", device: "lunibee" }, shard: [this.#options.shardId, this.#options.shardCount] }, s: null, t: null }); }
    /** Starts the heartbeat cadence and ACK timeout tracking. @param interval Heartbeat interval in milliseconds. @returns Nothing. */
    #startHeartbeat(interval: number): void { this.#clearHeartbeatTimers(); this.#heartbeatACK = true; this.#initialHeartbeat = setTimeout(() => this.#sendHeartbeat(), Math.random() * interval); this.#heartbeatTimer = setInterval(() => this.#sendHeartbeat(), interval); }
    /** Sends one Gateway heartbeat and starts ACK timeout tracking. @returns Nothing. */
    #sendHeartbeat(): void { this.#heartbeatACK = false; this.#heartbeatSentAt = Date.now(); if (!this.send({ op: GatewayOpcodes.Heartbeat, d: this.#sequence, s: null, t: null })) { this.#emitError(new GatewayError("Unable to send Gateway heartbeat because the WebSocket is not open.")); return; } this.#clearHeartbeatAckTimer(); this.#heartbeatAckTimer = setTimeout(() => { if (!this.#heartbeatACK) { const elapsed = Date.now() - this.#heartbeatSentAt; this.#emitError(new GatewayError(`Gateway heartbeat acknowledgement timed out after ${elapsed}ms.`)); try { this.#ws?.close(1001, "Heartbeat timeout"); } catch (error) { this.#emitError(error); } } }, this.#options.heartbeatAckTimeout); }
    /** Handles a WebSocket close and selects resume, identify, or stop behavior. @param ws Closed socket. @param code Discord close code. @returns Nothing. */
    #close(ws: WebSocket, code: number): void { if (this.#ws !== ws) return; this.#ws = undefined; this.#clearTimers(); const action = this.#closeAction(code); this.#emit("close", { code, action }); if (this.#closed || !this.#options.reconnect || action === "stop") { this.#setState(this.#closed ? "closed" : "disconnected"); if (this.#connectPromise) this.#settleConnect(new GatewayError(`Gateway closed before READY (code ${code}).`, code)); return; } if (action === "identify") { this.#sequence = null; this.#sessionId = undefined; } this.#setState("reconnecting"); this.#scheduleReconnect(); }
    /** Determines the correct recovery strategy for a Discord close code. @param code Discord close code. @returns Recovery action. */
    #closeAction(code: number): "resume" | "identify" | "stop" { if ([4004, 4010, 4011, 4012, 4013, 4014].includes(code)) return "stop"; if ([4007, 4009].includes(code)) return "identify"; return this.#sessionId && this.#sequence !== null ? "resume" : "identify"; }
    /** Schedules exponential-backoff reconnect when enabled. @returns Nothing. */
    #scheduleReconnect(): void { if (this.#closed || !this.#options.reconnect || this.#reconnectTimer) return; if (this.#attempt >= this.#options.maxReconnectAttempts) { this.#settleConnect(new GatewayError("Gateway reconnect attempts exhausted.")); this.#setState("disconnected"); return; } const delay = Math.min(this.#options.reconnectMaxDelay, this.#options.reconnectBaseDelay * 2 ** this.#attempt++) + Math.random() * 250; this.#reconnectTimer = setTimeout(() => { this.#reconnectTimer = undefined; this.#open(this.#resumeURL ?? "wss://gateway.discord.gg/?v=10&encoding=json"); }, delay); }
    /** Settles the pending connect promise exactly once. @param error Optional connection error. @returns Nothing. */
    #settleConnect(error?: GatewayError): void { const resolve = this.#resolveConnect; const reject = this.#rejectConnect; this.#resolveConnect = undefined; this.#rejectConnect = undefined; this.#connectPromise = undefined; if (error) reject?.(error); else resolve?.(); }
    /** Clears the heartbeat ACK timeout. @returns Nothing. */
    #clearHeartbeatAckTimer(): void { if (this.#heartbeatAckTimer) clearTimeout(this.#heartbeatAckTimer); this.#heartbeatAckTimer = undefined; }
    /** Clears heartbeat interval, initial delay, and ACK timeout timers. @returns Nothing. */
    #clearHeartbeatTimers(): void { if (this.#heartbeatTimer) clearInterval(this.#heartbeatTimer); if (this.#initialHeartbeat) clearTimeout(this.#initialHeartbeat); this.#clearHeartbeatAckTimer(); this.#heartbeatTimer = undefined; this.#initialHeartbeat = undefined; }
    /** Clears all Gateway lifecycle timers. @returns Nothing. */
    #clearTimers(): void { if (this.#reconnectTimer) clearTimeout(this.#reconnectTimer); if (this.#zombieTimer) clearInterval(this.#zombieTimer); this.#reconnectTimer = undefined; this.#zombieTimer = undefined; this.#clearHeartbeatTimers(); }
    /** Normalizes unknown connection failures into GatewayError. @param error Unknown failure. @returns Normalized Gateway error. */
    #normalizeError(error: unknown): GatewayError { return error instanceof GatewayError ? error : new GatewayError("Gateway connection failed.", undefined, { cause: error }); }
    /** Emits a normalized Gateway error. @param error Unknown failure. @returns Nothing. */
    #emitError(error: unknown): void { this.#emit("error", error instanceof Error ? error : new GatewayError(String(error))); }
    /** Emits an event while isolating listener failures. @param event Event name. @param data Event payload. @returns Nothing. */
    #emit(event: string, data: unknown): void { for (const listener of this.#listeners.get(event) ?? []) { try { const result = listener(data); if (result && typeof (result as PromiseLike<unknown>).then === "function") void Promise.resolve(result).catch(error => { if (event !== "error") this.#emitError(error); }); } catch (error) { if (event !== "error") this.#emitError(error); } } }
    /** Updates lifecycle state and emits a state-change event. @param next Next lifecycle state. @returns Nothing. */
    #setState(next: GatewayState): void { if (this.state === next) return; const previous = this.state; this.state = next; this.#emit("stateChange", { previous, next }); }
}
