version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

    groups:
      bun-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/bun"

    ignore:
      - dependency-name: "@types/bun"

  - package-ecosystem: "bun"
    directory: "/lunibee.js.org"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

    groups:
      docs-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

    groups:
      github-actions:
        patterns:
          - "*"