import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { identifier } from "./handlers.js";
import { paint, type IO } from "./io.js";

const SKIP = /\.(d|test|spec)\.[jt]s$/;

export interface CommandFile {
    /** Path relative to src/commands, e.g. `util/ping.ts`. */
    file: string;
    /** Import path from src/commands/index.ts. */
    path: string;
    importName: string;
}

export interface CommandDiscovery {
    commands: CommandFile[];
    /** Command files without a default export (they would register nothing). */
    missingDefault: string[];
}

async function walk(dir: string, prefix = ""): Promise<string[]> {
    let entries;
    try {
        entries = await readdir(dir, { withFileTypes: true });
    } catch {
        return [];
    }
    const found: string[] = [];
    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
        const relative = prefix + entry.name;
        if (entry.isDirectory())
            found.push(...(await walk(join(dir, entry.name), `${relative}/`)));
        else if (
            entry.isFile() &&
            /\.[jt]s$/.test(entry.name) &&
            !SKIP.test(entry.name) &&
            relative !== "index.ts" &&
            relative !== "index.js"
        )
            found.push(relative);
    }
    return found;
}

/** Finds command files under `commandsDir`; a `.ts` file wins over a `.js` beside it. */
export async function discoverCommands(
    commandsDir: string,
): Promise<CommandDiscovery> {
    const result: CommandDiscovery = { commands: [], missingDefault: [] };
    const seen = new Set<string>();
    const names = new Set<string>();
    const files = (await walk(commandsDir)).sort(
        (a, b) =>
            Number(a.endsWith(".js")) - Number(b.endsWith(".js")) ||
            a.localeCompare(b),
    );
    for (const file of files) {
        const base = file.slice(0, -3);
        if (seen.has(base)) continue;
        seen.add(base);
        const source = await Bun.file(join(commandsDir, file)).text();
        if (!/export\s+default\b|\bas\s+default\b/.test(source))
            result.missingDefault.push(file);
        let importName = identifier(`command_${base.replace(/\//g, "_")}`);
        for (let n = 2; names.has(importName); n++)
            importName = identifier(`command_${base.replace(/\//g, "_")}_${n}`);
        names.add(importName);
        result.commands.push({ file, path: `./${base}`, importName });
    }
    result.commands.sort((a, b) => a.path.localeCompare(b.path));
    return result;
}

/** The generated src/commands/index.ts for `commands`. */
export function commandsBinderSource(commands: readonly CommandFile[]): string {
    const imports = commands
        .map((c) => `import ${c.importName} from "${c.path}";`)
        .join("\n");
    const list = commands.map((c) => `    ${c.importName},`).join("\n");
    return `// Generated by \`lunibee create command\` / \`lunibee sync commands\`. Do not edit:\n// add, rename or remove files under src/commands/ and run \`lunibee sync commands\`.\nimport type { Client } from "lunibee";\n${imports ? `\n${imports}` : ""}\n\n/** Registers every command found under src/commands. Then call bot.commands.deploy() and bot.commands.listen(). */\nexport function registerCommands(bot: Client): void {\n  bot.commands.add(\n${list}\n  );\n}\n`;
}

export const commandsDir = (root: string) => join(root, "src", "commands");
export const commandsBinderPath = (root: string) =>
    join(commandsDir(root), "index.ts");

export interface CommandsBinderState {
    discovery: CommandDiscovery;
    expected: string;
    upToDate: boolean;
}

export async function commandsBinderState(
    root: string,
): Promise<CommandsBinderState> {
    const discovery = await discoverCommands(commandsDir(root));
    const expected = commandsBinderSource(discovery.commands);
    const file = Bun.file(commandsBinderPath(root));
    const current = (await file.exists()) ? await file.text() : null;
    return { discovery, expected, upToDate: current === expected };
}

export interface SyncCommandsOptions {
    dryRun?: boolean;
    /** Report only; exit code 1 when the binder is out of date. */
    check?: boolean;
}

/** `lunibee sync commands`. @returns The exit code. */
export async function syncCommands(
    io: IO,
    root: string,
    options: SyncCommandsOptions = {},
): Promise<number> {
    const state = await commandsBinderState(root);
    for (const file of state.discovery.missingDefault)
        io.err(
            `${paint(io, "yellow", "⚠")} commands/${file} has no default export`,
        );
    const count = state.discovery.commands.length;
    const summary = `${count} command${count === 1 ? "" : "s"}`;
    if (state.upToDate) {
        io.out(
            `${paint(io, "green", "✓")} commands/index.ts is up to date (${summary})`,
        );
        return 0;
    }
    if (options.check) {
        io.err(
            `${paint(io, "red", "✗")} commands/index.ts is out of date. Run \`lunibee sync commands\`.`,
        );
        return 1;
    }
    if (options.dryRun) {
        io.out(`• would update commands/index.ts (${summary})`);
        return 0;
    }
    await mkdir(commandsDir(root), { recursive: true });
    await writeFile(commandsBinderPath(root), state.expected);
    io.out(`${paint(io, "green", "✓")} updated commands/index.ts (${summary})`);
    return 0;
}
