/**
 * Runs every benchmark and writes the Benchmarks section of the docs site:
 *
 *   bun run build && bun scripts/bench-docs.ts
 *
 * One page per classification (Collection, Builders, Formatters, Gateway
 * events, REST, cache memory), plus an overview. The pages carry the run date,
 * runtime and the command that reproduces each table. Commit the result.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const out = join(root, "lunibee.js.org/src/content/docs/benchmarks");

async function run(command: string[], env: Record<string, string> = {}): Promise<string> {
    const proc = Bun.spawn(command, { cwd: root, env: { ...process.env, ...env }, stdout: "pipe", stderr: "pipe" });
    const [text, code] = await Promise.all([new Response(proc.stdout).text(), proc.exited]);
    if (code !== 0) throw new Error(`${command.join(" ")} failed: ${await new Response(proc.stderr).text()}`);
    return text.trim();
}

interface Row {
    group: string;
    name: string;
    ns: number | null;
}

const date = new Date().toISOString().slice(0, 10);
const runtime = `Bun ${Bun.version}`;
const rounds = 3;

// Median of several runs of the runtime benchmark.
const runs: Row[][] = [];
for (let i = 0; i < rounds; i++)
    runs.push(JSON.parse(await run([process.execPath, "scripts/bench-runtime.mjs", "--json"])).results);
const merged = new Map<string, { row: Row; samples: number[] }>();
for (const result of runs)
    for (const row of result) {
        if (row.ns === null) continue;
        const key = `${row.group}/${row.name}`;
        const entry = merged.get(key) ?? { row, samples: [] };
        entry.samples.push(row.ns);
        merged.set(key, entry);
    }
const rows = [...merged.values()].map(({ row, samples }) => {
    samples.sort((a, b) => a - b);
    return { ...row, ns: samples[samples.length >> 1]! };
});

function format(ns: number): string {
    if (ns >= 1_000_000) return `${(ns / 1_000_000).toFixed(2)} ms`;
    if (ns >= 1000) return `${(ns / 1000).toFixed(1)} µs`;
    return `${ns.toFixed(0)} ns`;
}

function table(group: string): string {
    const list = rows.filter((row) => row.group === group);
    return `| Operation | Median time |\n| --- | ---: |\n${list.map((row) => `| ${row.name.replace(/\|/g, "\\|")} | ${format(row.ns)} |`).join("\n")}`;
}

const header = (title: string, description: string) =>
    `---\ntitle: ${title}\ndescription: ${description}\n---\n\n`;
const meta = `Measured ${date} on ${runtime}, Linux, a shared CPU. Absolute times move by about ±20% between runs and machines: compare ratios and orders of magnitude, not single digits.`;

const pages: Record<string, string> = {};

pages["index.md"] =
    header("Benchmarks", "What Lunibee costs, by classification, and how to reproduce every number.") +
    `${meta}

Every page is generated by \`bun scripts/bench-docs.ts\` (after \`bun run build\`) and every table says which command reproduces it. The harnesses live in \`benchmarks/\` and \`scripts/\`, outside the published packages.

| Classification | What it measures | Page |
| --- | --- | --- |
| Collection | Reads, writes, scans and eviction, against discord.js and a plain \`Map\` | [Collection](/benchmarks/collection/) |
| Builders | Building and serialising embeds, components and commands | [Builders](/benchmarks/builders/) |
| Formatters | Mentions, timestamps and text styling helpers | [Formatters](/benchmarks/formatters/) |
| Gateway events | The cost of each dispatch the client handles, cache sync included | [Gateway events](/benchmarks/gateway-events/) |
| REST | Request scheduling against a fake Discord with real rate-limit windows | [REST](/benchmarks/rest/) |
| Cache memory | Heap kept per guild for small, medium and large guilds | [Cache memory](/benchmarks/cache-memory/) |

## Reading the numbers

- **Times are per call**, after a warm-up, as the median of ${rounds} runs.
- **Regressions.** \`bun run bench:compare\` re-runs the runtime benchmark, scales it by how fast this machine runs a plain \`Map\` compared with the committed baseline (\`docs/perf/\`), and warns on anything more than 15% slower. It runs in CI and only warns.
- **Why a fake Discord?** Network benchmarks depend on Discord's availability, so REST and Gateway figures use controlled fakes.
`;

const discordjs = await run([process.execPath, "benchmarks/collection.ts"]);
pages["collection.md"] =
    header("Collection benchmarks", "Lunibee's Collection against discord.js and a plain Map, and every Collection method.") +
    `${meta}

## Against discord.js

\`\`\`text
${discordjs}
\`\`\`

\`bun benchmarks/collection.ts\`: contenders take turns inside each round and the best run is kept, so the figures are steady on a busy machine. A \`ttl\` or \`maxSize\` collection does more work per write (a policy record per key); a plain one is within a small factor of \`Map\`.

## Every method

${table("Collection")}

\`bun run build && bun scripts/bench-runtime.mjs\`
`;

pages["builders.md"] =
    header("Builder benchmarks", "Cost of building and serialising Lunibee's builders.") +
    `${meta}

Each row builds the object and calls \`toJSON()\`. Builders validate as they go, so the cost grows with the number of options.

${table("Builders")}

\`bun run build && bun scripts/bench-runtime.mjs\`
`;

pages["formatters.md"] =
    header("Formatter benchmarks", "Cost of the mention, timestamp and text-style helpers.") +
    `${meta}

These are string builders; the costs are tens to hundreds of nanoseconds.

${table("Formatters")}

\`bun run build && bun scripts/bench-runtime.mjs\`
`;

const gateway = await run([process.execPath, "benchmarks/gateway-events.ts"]);
pages["gateway-events.md"] =
    header("Gateway event benchmarks", "What the client spends on each Gateway dispatch.") +
    `${meta}

## Core events

\`\`\`text
${gateway}
\`\`\`

\`bun benchmarks/gateway-events.ts\` feeds dispatch payloads straight to the client's handlers (no socket) and includes cache synchronisation.

## Every dispatch

Each row feeds one event to a client with the default cache.

${table("Gateway events")}

\`bun run build && bun scripts/bench-runtime.mjs\`
`;

const rest = await run([process.execPath, "benchmarks/rest-buckets.ts"]);
pages["rest.md"] =
    header("REST benchmarks", "Sequential against concurrent bucket scheduling, with a fake Discord that enforces real rate-limit windows.") +
    `${meta}

\`\`\`text
${rest}
\`\`\`

\`bun run bench:rest\`. Since 0.3.0 requests on a bucket whose limit is known run concurrently, up to its remaining allowance (\`concurrentBuckets: true\`, the default). The gain appears when the round trip is longer than the bucket's window divided by its limit. Pass \`concurrentBuckets: false\` for strict per-bucket ordering. A separate 10,000-request soak test (\`tests/rest.soak.test.ts\`) checks that fewer than 1% of requests are rate limited.
`;

const memory = await run([process.execPath, "benchmarks/cache-memory.ts"]);
pages["cache-memory.md"] =
    header("Cache memory benchmarks", "Heap kept per guild for small, medium and large guilds.") +
    `${meta}

\`\`\`text
${memory}
\`\`\`

\`bun benchmarks/cache-memory.ts\` feeds \`GUILD_CREATE\` payloads (roles, channels, members) to a client and reports the heap each guild keeps after a full GC. Users repeat across guilds, as they do on Discord. Members and their users dominate large guilds: turn off what a bot does not read with \`cache: { members: false }\` and the like.
`;

await mkdir(out, { recursive: true });
for (const [name, content] of Object.entries(pages)) await writeFile(join(out, name), content);
console.log(`Wrote ${Object.keys(pages).length} pages to ${out}`);
